### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Credential() 

### ISSUE THREAD

**Issue by henzan02** [atInisiatifZakat/whatsapp-qontak-php#2]
Halo, ini ada error Fatal error: Uncaught Error: Call to undefined function Credential() 
Saya menggunakan sample Non framework usage.

**Comment by nuradiyana** [comment]
Halo, contoh sudah di update, ada kurang `use`, bisa di coba kembali. trims

**Comment by SupianIDz** [comment]
kurang `new` pada inisiasi class `Credential`

![image](https://github.com/atInisiatifZakat/whatsapp-qontak-php/assets/37969970/8c71a604-3723-4475-afc3-7b48ee8017fc)

harusnya

```php
$credentials = new Credential('username', 'password', 'clientId', 'clientSecret');
```

**Comment by nuradiyana** [comment]
Trims @SupianIDz
