### ISSUE TITLE
Use Guzzle Instead HTTPlug

### ISSUE THREAD

**Issue by SupianIDz** [atInisiatifZakat/whatsapp-qontak-php#5]
is there any plan to replace HTTP Plug with Guzzle ?
- Non Framework use Guzzle
- Laravel Framework use the L[aravel HTTP Client](https://laravel.com/docs/10.x/http-client) which is based on Guzzle.

The benefits obtained when using the Laravel HTTP Client can do mocking easily for testing and logging requests on the [Telescope](https://laravel.com/docs/10.x/telescope).

**Comment by nuradiyana** [comment]
For now, there are no plans to change the http client, for Guzzle can we use the [Guzzle Adapter](https://docs.php-http.org/en/latest/clients/guzzle7-adapter.html) ?
